initial commit
odagonzpfm1/PFMCPP_Project6 pull request #1
Opened 2023-12-28 04:36 UTC by odagonzpfm1

odagonzpfm1

2023-12-29 07:10 UTC, matkatmusic requested changes

2023-12-29 07:10 UTC, matkatmusic commented on main.cpp
>          return nullptr;
D.R.Y.
You have written `return nullptr;` twice in this function.
Revise the logic such that you only write it once.
- [x] revise

2023-12-29 07:10 UTC, matkatmusic commented on main.cpp
> +    std::cout << "the smaller one is << " << smaller->name << ".\nIf compare() returns a nullptr, then nothing will print out."<< std::endl;
What do we always do before using a pointer?
- [ ] revise

2023-12-29 12:57 UTC, odagonzpfm1 commented on main.cpp
> +    std::cout << "the smaller one is << " << smaller->name << ".\nIf compare() returns a nullptr, then nothing will print out."<< std::endl;
Check its not null

2023-12-29 13:33 UTC, odagonzpfm1 commented on main.cpp
>          return nullptr;
DRY up the code, however I still get a compiler warning for not having all paths covered. I think I'm covering all the paths (<, >, ==) in the logic plus nullptr, however still looks weird not having a "catch all" return at the bottom. 
How would you go about it?

2024-01-02 06:16 UTC, matkatmusic requested changes

2024-01-02 06:16 UTC, matkatmusic commented on main.cpp
> +    }
```
if( smaller == nullptr )
{
    std::cout << "one or more arguments to the compare() function is a nullptr or all arguments' 'distance' member variable all have the same value." << std::endl;
}
else
{
    std::cout << "the smaller one is " << smaller->name << std::endl;
}
```
- [ ] revise

2024-01-03 06:31 UTC, matkatmusic approved these changes

2024-01-03 06:31 UTC, merged